### ISSUE TITLE
Add support for authentication oauth2

### ISSUE THREAD

**Issue by msegoviadev** [MarcosSegovia/MyWins#2]
Right now MyWins only supports request to the api provided without an authentication system.
As a result, not only the access would be opened to whoever is able to make a request to the app, opening the door to posible bot-request, DDoS Attacks (security issues) but also It does not provide support for different users, as they are sharing the same resource.

By adding oauth2 authentication we want to provide the authentication of the current user given a previous login through a request into the API from the current client. 
As a result of the login, a token will be generated to provide API visibility and user data while attaching it into the headers of every request to the endpoints of the API.

For now let's statically register users within the server and build the whole login and oauth2 implementation. Registration will come after.

**Comment by dixonwille** [comment]
@MarcosSegovia will you elaborate on this. Do you want to create an oauth service that other applications can connect to? Or do you want to connect to existing oauth services for users to login to?

**Comment by msegoviadev** [comment]
updated !

**Comment by dixonwille** [comment]
@MarcosSegovia this Issue should be split into two maybe three issues. 1 for allowing different users to use the app, 2 Authentication for authenticating a request, 3 Authorization to say the authenticated user has these rights.

**Comment by msegoviadev** [comment]
This is up and running since https://github.com/MarcosSegovia/MyWins/releases/tag/v0.2
